# Generated by Django 5.0.6 on 2024-08-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_productoffer_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='variant',
        ),
    ]
