# Generated by Django 5.0.6 on 2024-08-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_categoryoffer_is_active_and_more'),
        ('products', '0017_product_offer_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='variant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variant_offer', to='products.variant'),
        ),
    ]
