# Generated by Django 5.0.6 on 2024-08-12 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_productoffer_variant'),
        ('products', '0017_product_offer_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variant_offer', to='products.variant'),
        ),
    ]
