# Generated by Django 5.0.6 on 2024-08-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_alter_productoffer_variant'),
        ('products', '0018_variant_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='products.product'),
        ),
    ]
