# Generated by Django 5.0.6 on 2024-09-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_productoffer_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryOffer',
        ),
    ]
