# Generated by Django 5.0.6 on 2024-06-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='extra_amount',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='name',
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.CharField(default='white', max_length=100),
        ),
        migrations.AddField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='variant',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
    ]
