# Generated by Django 5.0.6 on 2024-06-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_variant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='name',
        ),
    ]
