# Generated by Django 5.0.6 on 2024-07-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_variant_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_count',
        ),
    ]
