# Generated by Django 5.0.6 on 2024-08-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_variant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_applied',
            field=models.BooleanField(default=False),
        ),
    ]
