# Generated by Django 5.0.6 on 2024-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='url_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
