# Generated by Django 5.0.6 on 2024-06-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categories_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='url_name',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
