# Generated by Django 5.0.6 on 2024-06-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_categories_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
