# Generated by Django 5.0.6 on 2024-06-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_categories_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
