# Generated by Django 5.0.6 on 2024-06-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_categories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
    ]
