# Generated by Django 5.0.6 on 2024-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_categories_cropping_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
