# Generated by Django 5.0.6 on 2024-06-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_categories_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='cropping',
        ),
    ]
