# Generated by Django 5.0.6 on 2024-06-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_remove_categories_cropping'),
        ('products', '0004_variant_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
