# Generated by Django 5.0.6 on 2024-06-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=9497355185, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
