# Generated by Django 5.0.6 on 2024-06-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0013_address_primary_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default=False, max_length=25),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=False, max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
