# Generated by Django 5.0.6 on 2024-07-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0015_rename_user_address_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
