# Generated by Django 5.0.6 on 2024-06-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_remove_customuser_date_of_join_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
