# Generated by Django 5.0.6 on 2024-06-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0012_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='primary_address',
            field=models.BooleanField(default=False),
        ),
    ]
