# Generated by Django 5.0.6 on 2024-06-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0014_address_address_address_name_address_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_address',
            new_name='user',
        ),
    ]
