# Generated by Django 5.0.6 on 2024-07-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0004_order_address_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='order_address',
        ),
    ]
