# Generated by Django 5.0.6 on 2024-07-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0008_order_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
