# Generated by Django 5.0.6 on 2024-07-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0012_coupon_max_amount_coupon_min_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_amount',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
