# Generated by Django 5.0.6 on 2024-07-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0017_order_refund_granted_order_refund_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
