# Generated by Django 5.0.6 on 2024-07-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0006_alter_order_order_address'),
        ('user_accounts', '0016_address_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_accounts.address'),
        ),
    ]
