# Generated by Django 5.0.6 on 2024-07-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0011_alter_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_amount',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_amount',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
