# Generated by Django 5.0.6 on 2024-08-03 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0018_remove_wallettransaction_wallet_delete_wallet_and_more'),
        ('user_accounts', '0016_address_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_accounts.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
