# Generated by Django 5.0.6 on 2024-08-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0019_order_address_alter_order_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
