# Generated by Django 5.0.6 on 2024-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_cart', '0020_alter_order_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
