# Generated by Django 5.0.6 on 2024-06-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_variant_category_remove_variant_extra_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='name',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
