# Generated by Django 5.0.6 on 2024-06-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_variant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
