# Generated by Django 5.0.6 on 2024-07-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_variant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='slug',
            field=models.SlugField(blank=True, unique=False),
        ),
    ]
