# Generated by Django 5.0.6 on 2024-07-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_variant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
