# Generated by Django 5.0.6 on 2024-07-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_variant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
