# Generated by Django 5.0.6 on 2024-07-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
