# Generated by Django 5.0.6 on 2024-07-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_variant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
