# Generated by Django 5.0.6 on 2024-08-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_offer_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
